on: [push, pull_request]
name: Test
jobs:
  build:
    runs-on: namespace-profile-ghostty-macos
    env:
      ZIG_LOCAL_CACHE_DIR: /zig/local-cache
      ZIG_GLOBAL_CACHE_DIR: /zig/global-cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Cross-compile the binary. We always use static building for this
      # because its the only way to access the headers.
      - name: Test
        run: nix develop -c zig build test --summary all
